# Generated by Django 5.0.6 on 2024-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0024_processedfeed_translate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalfeed',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the original feeds, multiple URLs will be numbered.', max_length=255),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='url',
            field=models.TextField(help_text='URL of the Atom or RSS feed. You can input multiple URLs separated by commas or newlines.', max_length=2048, unique=True),
        ),
    ]
